### PR TITLE
Fix Change Log TOC

### PR DESCRIPTION
**Pull request by cmazakas**
By updating the Jamfile, we can get the Unordered change log to render like the one in Core.

### CODE REVIEW

**Comment by glenfe** [comment]
I would probably have kept the changelog using [heading] instead of [section] and leave the TOC depth as it is now.

**Comment by pdimov** [comment]
Yep. Let's just get back to `[h2]` as it was before [the change](https://github.com/boostorg/unordered/commit/8ce147dcbdddc520c77f327a410eaa8b234e2a64).

**Comment by glenfe** [comment]
[heading] might be better than [h2] because it automatically chooses the heading size based on the current section depth.

**Comment by pdimov** [comment]
Since the Unordered docs are of the "integrated" variety, the local chunking parameter doesn't actually apply. They currently [look like this](https://www.boost.org/doc/libs/develop/doc/html/unordered.html). I think that we don't want this, so using `[heading]` seems the way to go.

**Pull request closed without merging**
