### PR TITLE
Update Appveyor from Boost.CI 

### PR DESCRIPTION
**Pull request by Flamefire**
Extracted from #114 to make the changes easier to handle

### CODE REVIEW

**Comment by Flamefire** [comment]
@cmazakas This and #114 are ready now. I'd suggest to merge them both at the same time (at least on GHA the 2nd commit/merge will cancel the CI run started by the first) and then merge develop to master, potentially after adjusting the `.codecov.yml` to your liking, see #114 for details. Only then the codecov settings will be in effect.

**Comment by pdimov** [comment]
@Flamefire In order to fix the Cygwin failure (marked as allowed now), we need to pass `include=` to `b2`, but at the moment boost-ci doesn't seem to have the `B2_INCLUDE` option: https://github.com/boostorg/boost-ci/blob/a5712f1268770e1a32e352d485247d0460145a3f/ci/build.bat#L13-L18

**Comment by Flamefire** [comment]
IMO this needs to be set in the Jamfiles. I wouldn't expect users to need to know which paths to pass to `include=`.

**Comment by pdimov** [comment]
I am the user in this case and I know which paths I need to pass to get Cygwin to work.

**Pull request merged**
